services:
  nginx:
    image: nginx:1.28
    ports:
      - 80:80
    depends_on:
      - php-fpm
    volumes:
      - /var/www/solt/back-solt:/var/www/
      - /var/www/solt/front-solt:/var/www/docker/front/front-solt
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/dockerFile/php.dockerfile
    volumes:
      - /var/www/solt/back-solt:/var/www/
    ports:
      - '9000:9000'
    depends_on:
      - postgres
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: aSdf514134f
      POSTGRES_DB: solt
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5431:5432'
    volumes:
      - ./db:/var/lib/postgresql/data/pgdata
